version: '3.8'

services:
  # --- API FLASK (BACKEND) ---
  api-dev:
    build:
      context: ./backend
      target: development
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=1
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: always

  api-prod:
    build:
      context: ./backend
      target: production
    ports:
      - "5001:5001"
    environment:
      - FLASK_DEBUG=0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    restart: always

  # --- WEB SERVER (FRONTEND) ---
  web:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    restart: always